### ISSUE TITLE
Setup fails on persistent runner when julia version updates

### ISSUE THREAD

**Issue by ianshmean** [julia-actions/setup-julia#32]
I have a self-hosted runner that persists between runs, which usually works with the setup-julia step.

However, when the julia version updates I get:
```
mkdir /home/ubuntu/julia
mkdir: cannot create directory ‘/home/ubuntu/julia’: File exists
##[error]The process 'mkdir' failed with exit code 1
```

I guess there are two  options:
1) Delete  the `/julia` dir before upgrade
2) Change to versioned `/julia1.4.2` dirs, but point a symlink from `julia` to the requested version

**Comment by SaschaMann** [comment]
Thanks for reporting this issue. I didn't know persistent build environments are even a thing. The 2nd suggestion sounds good to me, I'll implement it over the weekend.

**Comment by SaschaMann** [comment]
It'll take a bit longer. I want to add some checks that the correct version is in the path but I have to read up on how the testing framework actions use works to do it properly.

**Comment by SaschaMann** [comment]
Sorry, I haven't had enough time to finish it yet, so the next Julia update will break it once more. I'm still trying to understand the test framework and I'm a bit hesitant to change the install directory if I can't test it well because that could break hundreds of builds.

**Comment by SaschaMann** [comment]
Took me a lot longer, #46 should fix it.

I misused tool-cache before and effectively had two locations where Julia was installed. GitHub's tool-cache will handle the directories, as it has before, and Julia will be installed in `/opt/hostedtoolcache/version/arch`, e.g. `/opt/hostedtoolcache/julia/1.0.5/x64`. The difference is that the temporary directory where setup-julia installs it in, previously `~/julia` will now be a temporary directory and deleted once Julia has been installed to the tool-cache.

A follow-up PR will also check that if Julia has been installed already that version will be used, rather than reinstalling it. That should speed up builds on persistent runners significantly.

I don't have access to a self-hosted runner, so please let me know if this works once the next Julia version comes out.

**Comment by ianshmean** [comment]
Thanks! It's actually super easy to set up your local machine as a self hosted runner, if you wanted to try it out. 

I'll give it a go with ours and report back
