### ISSUE TITLE
File not found: index.jl

### ISSUE THREAD

**Issue by maleadt** [julia-actions/setup-julia#65]
I changed my actions to `use: setup-julia@master` to test the new `1.6-nightly` feature, https://github.com/JuliaGPU/CUDA.jl/commit/91db6b0f44975c9d061b2aab801ade9d4c624870, but that now fails with:

```
Run julia-actions/setup-julia@master
  with:
    version: 1.6-nightly
    arch: x64
    show-versioninfo: false
Error: File not found: '/home/runner/work/_actions/julia-actions/setup-julia/master/dist/index.js'
```

https://github.com/JuliaGPU/CUDA.jl/runs/1667299189?check_suite_focus=true

Should it still point to https://github.com/julia-actions/setup-julia/blob/master/lib/setup-julia.js?

**Comment by SaschaMann** [comment]
`@master` is intentionally setup to not include `index.js` and fail to discourage people from using it because it could randomly break their builds. This is (or was?) a best practice recommended by GitHub for actions.

I set #63 to be automerged and it was merged while I was sleeping, so I didn't have a chance to tag upon merging :D I've tagged a release now so it should work with `@v1` etc

I'd like to have some kind of continuous deployment from master but last time I checked it would have been too much effort to setup manually and there weren't any existing solutions that I liked.
