### ISSUE TITLE
Error on Windows and MacOS for Julia v1.5.4

### ISSUE THREAD

**Issue by junyuan-chen** [julia-actions/setup-julia#75]
With Julia version set to be 1 in the GitHub actions workflow file, I got errors for Windows and MacOS.

On Windows, I don't see an error message, but the workflow ends immediately.

On MacOS, I see the checksum error:
```
Run julia-actions/setup-julia@v1
Error: Checksum of downloaded file does not match the expected checksum from versions.json.
Expected: bd07f6c70d59a4491e481c205d6651e455b2e47b22547f901a9c2218b2718360
Got: 2f54aa030669ed47ca377a3ab866437540df337ad7e6df45f912bfd2b564d04a
```

There is no error for ubuntu.

I think this is related to the release of Julia v1.5.4 as it started to happen right after the release.

**Comment by SaschaMann** [comment]
An update to [`versions.json`](https://julialang-s3.julialang.org/bin/versions.json) fixed it, it should work now.

> On Windows, I don't see an error message, but the workflow ends immediately.

There's a bug in the error handling, it's meant to display a proper error message. I'll try to fix this.

> I think this is related to the release of Julia v1.5.4 as it started to happen right after the release.

Indeed. The problem was that the `versions.json` file, which contains checksums, download URLs etc for each version, was rebuilt shortly after a release was tagged in [julialang/julia](https://github.com/julialang/julia) but before the binaries were available (in case of Windows) or notarised (on macOS).
